
libdbwrapper:libhiredis
libEPSNSRData:libNSRBaseFramework
libIcmCommonUtils:libbracket_read_pure
libKMFSecurity:libencoderDecoder
libregdbwrapper:libhiredis
libsecUtil:libencoderDecoder
libSoapEncodeDecoder:libAtt_Gsoap
ums_mt:libImsApplCliCommon libyaml-cpp libbase libbracket_read_pure libcrypto_wrapper libhepencoder libcscfbase libsipurisupport libmcfshuserdata libxmltpscanner libsipparser libUMSstrcCframe libTrcAgentShCut libdbwrapper libhiredis libstraceapi libExtnCallback libcme libDiaclConf libdiacl libDiaCommon libDiadictionary libdiabmp libdiacl_shp libDiaAvpValidators libDiaConfParser libRouting libIWFConfig libepcIwf_mt libUMSadp libUMSArrayCounter libUMSctf libUMSctm libUMSdba_tp_hssd libUMSdbl_mt libUMSdbm libUMSErrorLog libCFGmngr_mt libUMSlip libUMSmpp libUMSmsp libLdapCtxUtil_mt libUMSolclient libUMSolh_mt libUMSrap libUMShd libUMScaveaka libUMSmap libUMScommon libUMSs6 libUMSs6c libUMSs6mn libUMSs6t libUMSslh libUMSswx libUMSwx libUMScx libUMSradius libUMSsh libUMSzh libUMStrigeps libUMStrigims libUMSsys_mt libUMStpe_mt libUMStppd_mt libNSRBaseFramework libEPSNSRData libStdEncoDeco libCNDeploymentType libCNNetworkConfig libUMSdic libUMSdic_common libAtt_GsoapMT libMessageContainer libMessageFormatter libTFRFormatterHelper libLdapStub libNemStub libNssStub libRtpStub libTestDriver libMessageValidator libKMFSecurity libAlbCommonUtils libencoderDecoder libIcmCommonUtils libOlcmDataAccess libsecUtil
