#!/bin/bash
#
# make-versionstamp.sh -- emit a .cpp with a compile-time-composed
# `__gm_versionstamp_<target>__` global that carries pkg version info
# into the final binary.  Recover from any linked-in artefact with:
#
#     strings <artefact> | grep GM_VERSIONSTAMP:
#
# Design: emit a small .cpp that `#include`s each pkg's auto-
# generated component header, then composes a single const char* by
# adjacent-string-literal concatenation.  The macros (P1_NAME,
# P1_PKG_VERSION, P2_NAME, P2_PKG_VERSION, ...) are expanded by the
# C++ preprocessor at compile time -- so the resulting string
# embeds the exact values each header declared, without shell-
# substituting them here (which would silently go stale if a
# header regenerated without the versionstamp .cpp also
# regenerating).
#
# Multi-pkg targets are supported: if the same lib is bundled by
# pkg-p1 AND pkg-p2 (both XML-mode), it embeds BOTH pkgs' identity.
# This works because pkg-xml.py now emits prefixed macros
# (P1_NAME + P2_NAME) and per-pkg include guards
# (COMPONENT_H_P1_INCLUDED / _P2_INCLUDED), so multiple component.h
# in one TU coexist -- see pkg-xml.py's _render_component_header
# docstring of that Python script.
#
# Usage:
#     make-versionstamp.sh <output.cpp> <target-name> [pkg-header ...]
#
# pkg-header is a full path to a `<pkg-name>/component.h` file (as
# emitted by pkg-xml.py --header-out).  The script recovers each
# header's macro prefix from the `pkg-xml prefix: <PREFIX>` marker
# comment at the top of the header itself -- so the versionstamp
# tracks whatever prefix scheme pkg-xml.py picks (currently: pkg
# name's last dot/hyphen segment uppercased, e.g. P2, ALPHA).

set -e

if [ $# -lt 2 ]; then
    echo "Usage: $0 <output.cpp> <target-name> [pkg-header ...]" >&2
    exit 1
fi

output="$1"
target="$2"
shift 2

# C-safe symbol name: any non-alnum -> underscore.  `printf '%s'`
# rather than `echo` here so a trailing newline doesn't leak into the
# symbol (`echo test-t2 | tr...` would emit `test_t2_`).
sym=$(printf '%s' "$target" | tr -c 'A-Za-z0-9' '_')

# Compose the .cpp into a temp file first, then move -- so a partial
# write doesn't leave a broken .cpp on disk if the shell is killed.
tmp="${output}.tmp.$$"

# `pkg_prefix <path-to-component.h>` extracts the PREFIX from the
# `pkg-xml prefix: <PREFIX>` marker line pkg-xml.py bakes in.
# Fall back to the containing directory name (uppercased, non-alnum
# to _) if the marker isn't there -- keeps the script robust against
# hand-written or older headers.
pkg_prefix() {
    local hdr="$1"
    local p
    p=$(sed -n 's|^[[:space:]]*/\*[[:space:]]*pkg-xml prefix:[[:space:]]*\([A-Za-z0-9_]*\).*|\1|p' \
        "$hdr" 2>/dev/null | head -1)
    if [ -z "$p" ]; then
        p=$(basename "$(dirname "$hdr")" | tr -c 'A-Za-z0-9' '_' | tr 'a-z' 'A-Z')
    fi
    printf '%s' "$p"
}

{
    echo '/*'
    echo ' * Auto-generated by make-versionstamp.sh -- DO NOT EDIT.'
    echo " * Emitted at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo " * pkgs: $#"
    echo ' */'
    echo ''

    # Include every pkg-header.  Each has its own per-pkg guard
    # (COMPONENT_H_<PREFIX>_INCLUDED) so multiple headers coexist in
    # this TU without collision.  Use path-qualified include so a
    # multi-pkg TU doesn't rely on which pkg's -I appears first in
    # CCFLAGS (short form `#include <component.h>` would pick one
    # arbitrarily and the unprefixed aliases would silently point at
    # that one pkg only).
    for hdr in "$@"; do
        pkg_dir=$(basename "$(dirname "$hdr")")
        echo "#include <${pkg_dir}/component.h>"
    done
    echo ''
    # File-scope const with an initializer is already a definition
    # emitted into .rodata; skip `extern` (redundant + generates a
    # gcc warning) and `static` (which risks optimize-out on some
    # compilers).  Symbol name doesn't matter for `strings` recovery
    # -- we grep the string payload, not the symbol.
    # Layout: target=... | (pkg blocks grouped) | built=... host=...
    # Target-first + pkg-first keeps the identity fields together so a
    # human eyeballing `strings ... | grep GM_VERSIONSTAMP:` can read
    # them without scrolling past build metadata.  build/host live at
    # the tail because they're forensics, not identity.
    echo "const char *__gm_versionstamp_${sym}__ ="
    echo "    \"GM_VERSIONSTAMP:\""
    echo "    \" target=${target}\""

    for hdr in "$@"; do
        prefix=$(pkg_prefix "$hdr")
        pkg_dir=$(basename "$(dirname "$hdr")")
        echo "    /* pkg block: ${pkg_dir} (prefix ${prefix}) */"
        echo "    \" pkg=\" ${prefix}_PKG_NAME"
        echo "    \" ver=\" ${prefix}_PKG_VERSION"
        echo "    \" (\" ${prefix}_PKG_RELEASE \")\""
    done

    echo "    \" built=$(date -u +%Y-%m-%dT%H:%M:%SZ)\""
    echo "    \" host=$(hostname 2>/dev/null || echo unknown)\""
    echo '    "";'
} > "$tmp"

mv -f "$tmp" "$output"
